[global]
excludes = [
  ".direnv",
  ".git",
  ".jj",
  ".codegraph",
  "result*",
  "node_modules",
  "*.lock"
]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
options = ["format", "--write"]
includes = ["*.css", "*.json"]

[formatter.markdown]
command = "prettier"
options = ["--write"]
includes = ["*.md"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]
