[global]
excludes = ["package-lock.json", "flake.lock", "secrets/**", ".sops.yaml"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
options = ["format", "--write"]
includes = ["*.css", "*.json", "*.jsonc", "*.js", "*.ts", "*.mjs"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.md", "*.yaml", "*.yml"]

[formatter.toml]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.sh]
command = "shfmt"
options = ["--write"]
includes = ["*.sh"]
