name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - &checkout
        uses: actions/checkout@v7
      - &install-nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - &nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: fmt
        run: nix-shell shell.nix --run "treefmt --ci"

  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - *checkout
      - *install-nix
      - *nix-cache
      - name: lint
        run: nix-shell shell.nix --run "npm ci && just lint"

  flake-check:
    name: flake check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - *checkout
      - *install-nix
      - *nix-cache
      - name: flake check
        run: nix flake check --all-systems --show-trace
